apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-js1
  template:
    metadata:
      labels:
        app: node-js1
    spec:
      containers:
      - name: node-js
        image: sandip9292/node-js-sample:1.0
        volumeMounts:
        - name: node-js-storage
          mountPath: /usr/src/app/data
      volumes:
      - name: node-js-storage
        persistentVolumeClaim:
          claimName: node-js-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: node-js-sample
spec:
  type: NodePort
  selector:
    app: node-js1  # Updated to match the deployment's labels
  ports:
    - port: 5000          # The port that the service will expose
      targetPort: 5000    # The port on the container
      nodePort: 30007     # The port on which the service will be exposed on the node